"""MkDocs hooks for the WinHint site (``mkdocs.yml`` → ``hooks``).

:func:`on_page_markdown` rewrites relative links so that pages can keep the links that
work on GitHub (relative to their source file) and still pass ``mkdocs build --strict``.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sitemap  # noqa: E402



def on_config(config):
    """Work around an mkdoxy 1.2.8 bug before any plugin runs.

    mkdoxy buckets classes by the first character of their name and only knows letters
    and ``~_@\\``. Doxygen names an anonymous struct bound to a variable
    (``static struct { … } G;``) ``[struct].G``, which made the class index raise
    ``KeyError: '['``. Extend the bucket alphabet with every printable character.

    Args:
        config: Site configuration (returned unchanged).

    Returns:
        The configuration.
    """
    import string

    from mkdoxy import generatorBase

    extra = "".join(c for c in string.printable if c not in generatorBase.LETTERS and not c.isspace())
    generatorBase.LETTERS += extra
    return config


_INLINE_CODE = re.compile(r"(`+)(.+?)\1")
_REF_PAIR = re.compile(r"\](\s*)\[")
_ANON_LINK = re.compile(r"\[([^\]]*)\]\(#[a-z]+-@[0-9]+\)")


def _escape_subscripts(markdown: str) -> str:
    """Escape ``][`` (and ``] [``) outside code in Doxygen-generated pages.

    C text such as ``W[K][N]`` or a usage line like ``[-k K][-c cpulist]`` looks like a
    Markdown reference link, which mkdocs-autorefs then reports as an unresolved
    cross-reference. Writing ``]\\[`` renders the same characters without the link
    semantics. Fenced blocks and inline code spans are left untouched. Links to the
    anchors of anonymous enums (``#enum-@123…``), which mkdoxy emits but never defines,
    are reduced to their text.

    Args:
        markdown: Page source generated by mkdoxy.

    Returns:
        The page source with the ``[`` of every ``][`` / ``] [`` outside code escaped.
    """
    markdown = _ANON_LINK.sub(r"\1", markdown)
    out, in_fence = [], False
    for line in markdown.splitlines(keepends=True):
        if sitemap.FENCE.match(line.lstrip()):
            in_fence = not in_fence
        if in_fence or not _REF_PAIR.search(line):
            out.append(line)
            continue
        pieces, last = [], 0
        for m in _INLINE_CODE.finditer(line):
            pieces.append(_REF_PAIR.sub(r"]\1\\[", line[last:m.start()]))
            pieces.append(m.group(0))
            last = m.end()
        pieces.append(_REF_PAIR.sub(r"]\1\\[", line[last:]))
        out.append("".join(pieces))
    return "".join(out)


def on_page_markdown(markdown, page, config, files):
    """Rewrite the links of one ``docs/`` page.

    Args:
        markdown: Page source.
        page: The MkDocs page being rendered.
        config: Site configuration (unused).
        files: Site files (unused).

    Returns:
        The page source with links rewritten by :func:`sitemap.rewrite_links`.
    """
    src = page.file.src_uri
    if src.startswith("api/cpp/") and src.count("/") > 2:     # mkdoxy pages
        return _escape_subscripts(markdown)
    if page.file.generated_by:              # API pages: nothing to rewrite
        return markdown
    return sitemap.rewrite_links(markdown, f"docs/{src}", src)
